### ISSUE TITLE
Extend the 30 day data availability for the daily average - Watercourse discharge/levels data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#18]
Currently the Watercourse discharge and levels have a 30 day max data availability for the daily average. 
If possible, that should be increased to maximum available from the BoM service.

**Comment by AnaBelgun** [comment]
@kring - this is requested for the DEA-TerriaCube (to complete the testing of the NEII feature)

**Comment by stevage** [comment]
Ok, so checking my understanding here, the issue is that on NEII Terria Cube, in the Watercourse Discharge item, the three "Daily" options (measures? I can't remember the right term) always have a fixed range of 30 days, instead of...whatever the maximum available is. We want to maximise them.

<img width="1019" alt="Screenshot 2019-04-15 10 08 10" src="https://user-images.githubusercontent.com/678344/56101357-635f3e80-5f66-11e9-9fe0-d4b3e79f76c0.png">

**Comment by stevage** [comment]
Ok, so, it's definitely possible to increase it. Currently we're sending through a parameter like `<gml:beginPosition>2019-03-14T00:10:11Z</gml:beginPosition>`, and if we change that to earlier, we get a longer time series.

Next questions for me:

- How do we work out what "maximum" is
- How to actually about changing that parameter.

**Comment by stevage** [comment]
Ok, this turns out to be insanely easy, just removing this line:

> "defaultDuration": "32d"

The issue specified "average", but I assume we should do the same thing for the "minimum" and "maximum" layers, and for both the HRS and "all" catalog items (and discharge and. That makes 3 x 2 x 2 = 12 layers affected.
